services:
  audioseal:
    build:
      context: .
      dockerfile: src/plugins/models/audio_seal/Dockerfile
    ports:
      - "${AUDIOSEAL_PORT}:${AUDIOSEAL_PORT}" # Reads from .env
    environment:
      - APP_PORT=${AUDIOSEAL_PORT} # Injects into container

  silentcipher:
    build:
      context: .
      dockerfile: src/plugins/models/silent_cipher/Dockerfile
    ports:
      - "${SILENTCIPHER_PORT}:${SILENTCIPHER_PORT}"
    environment:
      - APP_PORT=${SILENTCIPHER_PORT}

  wavmark:
    build:
      context: .
      dockerfile: src/plugins/models/wavmark/Dockerfile
    ports:
      - "${WAVMARK_PORT}:${WAVMARK_PORT}"
    environment:
      - APP_PORT=${WAVMARK_PORT}

  aware:
    build:
      context: .
      dockerfile: src/plugins/models/aware/Dockerfile
    ports:
      - "${AWARE_PORT}:${AWARE_PORT}"
    environment:
      - APP_PORT=${AWARE_PORT}

  vae:
    build:
      context: .
      dockerfile: src/plugins/attacks/vae/Dockerfile
    ports:
      - "${VAE_PORT}:${VAE_PORT}"
    environment:
      - APP_PORT=${VAE_PORT}

  diffusion:
    build:
      context: .
      dockerfile: src/plugins/attacks/diffusion/Dockerfile
    ports:
      - "${DIFFUSION_PORT}:${DIFFUSION_PORT}"
    environment:
      - APP_PORT=${DIFFUSION_PORT}

  speech_tokenization:
    build:
      context: .
      dockerfile: src/plugins/attacks/speech_tokenization/Dockerfile
    ports:
      - "${SPEECH_TOKENIZATION_PORT}:${SPEECH_TOKENIZATION_PORT}"
    environment:
      - APP_PORT=${SPEECH_TOKENIZATION_PORT}

  neural_vocoder:
    build:
      context: .
      dockerfile: src/plugins/attacks/neural_vocoder/Dockerfile
    ports:
      - "${NEURAL_VOCODER_PORT}:${NEURAL_VOCODER_PORT}"
    environment:
      - APP_PORT=${NEURAL_VOCODER_PORT}

  speech_enhancement1:
    build:
      context: .
      dockerfile: src/plugins/attacks/speech_enhancement_1/Dockerfile
    ports:
      - "${SPEECH_ENHANCEMENT_PORT1}:${SPEECH_ENHANCEMENT_PORT1}"
    environment:
      - APP_PORT=${SPEECH_ENHANCEMENT_PORT1}

  speech_enhancement2:
    build:
      context: .
      dockerfile: src/plugins/attacks/speech_enhancement_2/Dockerfile
    ports:
      - "${SPEECH_ENHANCEMENT_PORT2}:${SPEECH_ENHANCEMENT_PORT2}"
    environment:
      - APP_PORT=${SPEECH_ENHANCEMENT_PORT2}
    mem_limit: 12g
    memswap_limit: 16g
  
  timbrewm:
    build:
      context: .
      dockerfile: src/plugins/models/timbrewm/Dockerfile
    ports:
      - "${TIMBREWM_PORT}:${TIMBREWM_PORT}"
    environment:
      - APP_PORT=${TIMBREWM_PORT}

  perth:
    build:
      context: .
      dockerfile: src/plugins/models/perth/Dockerfile
    ports:
      - "${PERTH_PORT}:${PERTH_PORT}"
    environment:
      - APP_PORT=${PERTH_PORT}


  network_transmission:
    build:
      context: .
      dockerfile: src/plugins/attacks/network_transmission/Dockerfile
    ports:
      - "${NETWORK_TRANSMISSION_PORT}:${NETWORK_TRANSMISSION_PORT}"
    environment:
      - NETWORK_TRANSMISSION_PORT=${NETWORK_TRANSMISSION_PORT}
    cap_add:
      - NET_ADMIN
